// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type PortfolioHolding struct {
	Ticker    string
	Name      string
	Weight    string
	Comment   sql.NullString
	Price     string
	UpdatedDt time.Time
	AddedDt   time.Time
	Return    sql.NullString
}
