[project]
name = "agent"
version = "0.1.0"
description = "claude himself"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "openai>=1.97.1",
    "strands-agents>=1.0.1",
    "strands-agents-tools>=0.2.1",
]
