name: Update HTML from Markdown

on:
  push:
    paths:
      - 'agent/md/indices/GPT20.md'
    branches:
      - master

jobs:
  update-html:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Convert markdown to HTML
      run: |
        pip install markdown
        python3 << 'EOF'
        import markdown
        import re
        
        # Read the markdown file
        with open('agent/md/indices/GPT20.md', 'r') as f:
            content = f.read()
        
        # Convert markdown to HTML
        html_body = markdown.markdown(content)
        
        # Create full HTML document
        full_html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GPT20 Stock Index</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            line-height: 1.6;
            color: #333;
        }}
        h1 {{ color: #2c3e50; }}
        h2 {{ color: #34495e; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        h3 {{ color: #7f8c8d; }}
        strong {{ color: #2980b9; }}
        ol li {{ margin-bottom: 10px; }}
        em {{ font-style: italic; color: #7f8c8d; }}
    </style>
</head>
<body>
    <div id="content">
        {html_body}
    </div>
</body>
</html>'''
        
        # Write to docs/index.html
        with open('docs/index.html', 'w') as f:
            f.write(full_html)
        EOF
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/index.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update HTML from GPT20.md"
          git push
        fi