name: Update HTML from Markdown

on:
  push:
    paths:
      - 'agent/md/indices/GPT20.md'
    branches:
      - master

jobs:
  update-html:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Convert markdown to HTML
      run: python3 .github/scripts/convert.py
        
    - name: Commit changes
      run: |
        git config user.email 'action@github.com'
        git config user.name 'GitHub Action'
        git add docs/index.html
        git diff --staged --quiet || (git commit -m 'Auto-update HTML from GPT20.md' && git push)