name: Update HTML from Markdown

on:
  push:
    paths:
      - 'agent/md/indices/GPT20.md'
    branches:
      - master

jobs:
  update-html:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Convert markdown to HTML
      run: |
        python3 -c "
        import re
        
        # Read the markdown file
        with open('agent/md/indices/GPT20.md', 'r') as f:
            content = f.read()
        
        # Simple markdown to HTML conversion
        html_content = content
        html_content = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html_content, flags=re.MULTILINE)
        html_content = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html_content, flags=re.MULTILINE) 
        html_content = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html_content, flags=re.MULTILINE)
        html_content = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html_content)
        html_content = re.sub(r'_(.+?)_', r'<em>\1</em>', html_content)
        html_content = re.sub(r'^(\d+)\. (.+)$', r'<li>\2</li>', html_content, flags=re.MULTILINE)
        html_content = re.sub(r'^- (.+)$', r'<li>\1</li>', html_content, flags=re.MULTILINE)
        html_content = html_content.replace('\n\n', '</p><p>')
        html_content = '<p>' + html_content + '</p>'
        html_content = html_content.replace('<p><h', '<h').replace('</h1></p>', '</h1>').replace('</h2></p>', '</h2>').replace('</h3></p>', '</h3>')
        html_content = html_content.replace('<p><li>', '<ol><li>').replace('</li></p>', '</li></ol>')
        html_content = re.sub(r'</ol>\s*<ol>', '', html_content)
        
        # Create full HTML
        full_html = '''<!DOCTYPE html>
<html lang=\"en\">
<head>
    <meta charset=\"UTF-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
    <title>GPT20 Stock Index</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }
        h1 { color: #2c3e50; }
        h2 { color: #34495e; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        h3 { color: #7f8c8d; }
        strong { color: #2980b9; }
        ol li { margin-bottom: 10px; }
        em { font-style: italic; color: #7f8c8d; }
    </style>
</head>
<body>
    <div id=\"content\">
        ''' + html_content + '''
    </div>
</body>
</html>'''
        
        # Write to docs/index.html
        with open('docs/index.html', 'w') as f:
            f.write(full_html)
        "
        
    - name: Commit changes
      run: |
        git config user.email 'action@github.com'
        git config user.name 'GitHub Action'
        git add docs/index.html
        git diff --staged --quiet || (git commit -m 'Auto-update HTML from GPT20.md' && git push)